"""empty message

Revision ID: 1549c2996920
Revises: 204e81c58ea2
Create Date: 2019-12-12 20:44:09.713894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1549c2996920'
down_revision = '204e81c58ea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('artist', sa.String(length=160), nullable=False),
    sa.Column('genre', sa.String(length=160), nullable=False),
    sa.Column('danceability', sa.Float(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('loudness', sa.Float(), nullable=True),
    sa.Column('speechness', sa.Float(), nullable=True),
    sa.Column('acousticness', sa.Float(), nullable=True),
    sa.Column('instrumentalness', sa.Float(), nullable=True),
    sa.Column('liveness', sa.Float(), nullable=True),
    sa.Column('valence', sa.Float(), nullable=True),
    sa.Column('tempo', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.alter_column('feature', 'description',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('feature', 'type',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
    op.alter_column('video', 'search',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('video', 'url',
               existing_type=sa.VARCHAR(length=160),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'url',
               existing_type=sa.VARCHAR(length=160),
               nullable=True)
    op.alter_column('video', 'search',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('feature', 'type',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)
    op.alter_column('feature', 'description',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.drop_table('metadata')
    # ### end Alembic commands ###
