"""add encoding table

Revision ID: 8acdc3063d41
Revises: 5b4c73da0ebd
Create Date: 2020-02-12 21:17:17.421535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8acdc3063d41'
down_revision = '5b4c73da0ebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encoding',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('seq_no', sa.Integer(), nullable=False),
    sa.Column('value', postgresql.DOUBLE_PRECISION(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('video_id', 'seq_no')
    )
    op.drop_column('meta', 'genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meta', sa.Column('genre', sa.VARCHAR(length=160), autoincrement=False, nullable=False))
    op.drop_table('encoding')
    # ### end Alembic commands ###
