"""remove stdev, add seq_no in segmentfeatures

Revision ID: 9838f01ccec8
Revises: 3dc3c23f36a1
Create Date: 2020-01-12 19:00:16.234040

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9838f01ccec8'
down_revision = '3dc3c23f36a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segment_features', sa.Column('seq_no', sa.Integer(), nullable=False))
    op.drop_column('segment_features', 'stdev')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segment_features', sa.Column('stdev', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('segment_features', 'seq_no')
    # ### end Alembic commands ###
