"""add stdev column in segmentfeatures

Revision ID: 99751f48a936
Revises: c13f36601ce1
Create Date: 2020-01-11 18:25:02.543940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99751f48a936'
down_revision = 'c13f36601ce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segment_features', sa.Column('stdev', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('segment_features', 'stdev')
    # ### end Alembic commands ###
