"""add weight field

Revision ID: b9fefa1a0da0
Revises: 99f04589b35c
Create Date: 2019-12-16 20:22:46.752198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9fefa1a0da0'
down_revision = '99f04589b35c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature', sa.Column('weight', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feature', 'weight')
    # ### end Alembic commands ###
